# Generated by Django 2.1.10 on 2021-07-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210704_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ref_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
