# Generated by Django 2.1.10 on 2021-08-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_list', to='products.Product'),
        ),
    ]
